---
  - name: Update apt
    sudo: yes
    apt:  update_cache=yes

  - name: Install system packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items:
      - wget
      - build-essential
      - python-software-properties

  - name: Update apt again
    sudo: yes
    apt:  update_cache=yes

  - name: Install extra packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items: "{{ sys_packages }}"

  - name: Ensure bin folder is writable
    sudo: yes
    file: path=/usr/local/bin owner=root group=root mode=0777 state=directory
