---
composer_path: /usr/local/bin/composer
composer_keep_updated: false
composer_version: ''

# The directory where global packages will be installed.
composer_home_path: '~/.composer'
composer_home_owner: vagrant
composer_home_group: vagrant

# usage; the 'release' is optional, and defaults to '@stable'.
composer_global_packages: []
  # - { name: phpunit/phpunit, release: "4.7.x" }
  # - { name: phpunit/phpunit, release: "@stable" }

composer_add_to_path: true
