---
  - name: Install nginx
    sudo: yes
    apt:  pkg=nginx state=latest

  - name: Ensure nginx log directory exists
    sudo: yes
    file: dest=/var/log/nginx/{{ nginx.server_name }} state=directory

  - name: Change default nginx site
    sudo: yes
    template: src=default.tpl dest=/etc/nginx/sites-available/{{ nginx.server_name }}.conf
    notify: restart nginx
