---
  - name: Add nginx repository for Ubuntu
    become: true
    apt_repository: repo={{ nginx.nginx_ppa }}

  - name: Update apt
    become: yes
    apt: update_cache=yes

  - name: Install nginx
    sudo: yes
    apt:  pkg=nginx state=latest

  - name: Ensure nginx log directory exists
    sudo: yes
    file: dest=/var/log/nginx/{{ nginx.server_name }} state=directory

  - name: Change default nginx site
    sudo: yes
    template: src={{php_version}}_vhost.tpl dest=/etc/nginx/sites-available/{{ nginx.server_name }}.conf
    when: php_version == "php5" or php_version == "php7"

  - name: Create symlink for {{ nginx.server_name }}
    sudo: yes
    file: src=/etc/nginx/sites-available/{{nginx.server_name}}.conf dest=/etc/nginx/sites-enabled/{{nginx.server_name}}.conf state=link
    notify: restart nginx
    when: php_version == "php5" or php_version == "php7"